// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechHaven.Data;

#nullable disable

namespace TechHaven.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124233550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechHaven.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechHaven.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/categories/cpu.jpg",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/categories/gpu.jpg",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/categories/motherboard.jpg",
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/categories/ram.jpg",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/categories/storage.jpg",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/categories/psu.jpg",
                            Name = "Power Supply"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/categories/cooling.jpg",
                            Name = "Cooling"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/categories/case.jpg",
                            Name = "Case"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/categories/peripheral.jpg",
                            Name = "Peripheral"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/categories/monitor.jpg",
                            Name = "Monitor"
                        });
                });

            modelBuilder.Entity("TechHaven.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TechHaven.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SpecsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "6-core mid-range CPU with great single-thread performance.",
                            ImageUrl = "/images/products/intel_i5_12400f.jpg",
                            Name = "Intel Core i5-12400F",
                            Price = 229.99m,
                            SpecsJson = "{\"Cores\":6,\"Threads\":12,\"BaseClock\":\"2.5GHz\",\"BoostClock\":\"4.4GHz\",\"Socket\":\"LGA1700\",\"Manufacturer\":\"Intel\"}",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Affordable 6-core Ryzen CPU with excellent gaming performance.",
                            ImageUrl = "/images/products/amd_ryzen_5600x.jpg",
                            Name = "AMD Ryzen 5 5600X",
                            Price = 199.99m,
                            SpecsJson = "{\"Cores\":6,\"Threads\":12,\"BaseClock\":\"3.7GHz\",\"BoostClock\":\"4.6GHz\",\"Socket\":\"AM4\",\"Manufacturer\":\"AMD\"}",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "12-core high-end CPU suitable for gaming and content creation.",
                            ImageUrl = "/images/products/intel_i7_12700k.jpg",
                            Name = "Intel Core i7-12700K",
                            Price = 699.99m,
                            SpecsJson = "{\"Cores\":12,\"Threads\":20,\"BaseClock\":\"3.6GHz\",\"BoostClock\":\"5.0GHz\",\"Socket\":\"LGA1700\",\"Manufacturer\":\"Intel\"}",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Great value GPU for 1080p & 1440p gaming.",
                            ImageUrl = "/images/products/asus_rtx3060.jpg",
                            Name = "ASUS TUF Gaming GeForce RTX 3060",
                            Price = 529.99m,
                            SpecsJson = "{\"VRAM\":\"12GB\",\"BoostClock\":\"1.78GHz\",\"PCIe\":\"4.0\",\"Brand\":\"Nvidia\",\"Manufacturer\":\"ASUS\"}",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "High-end Nvidia GPU for 4K gaming and heavy workloads.",
                            ImageUrl = "/images/products/msi_rtx4080.jpg",
                            Name = "MSI GeForce RTX 4080 SUPER",
                            Price = 2699.99m,
                            SpecsJson = "{\"VRAM\":\"16GB\",\"BoostClock\":\"2.55GHz\",\"PCIe\":\"4.0\",\"Brand\":\"Nvidia\",\"Manufacturer\":\"MSI\"}",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Powerful AMD GPU for 1440p gaming with ray tracing.",
                            ImageUrl = "/images/products/gigabyte_6700xt.jpg",
                            Name = "Gigabyte Radeon RX 6700 XT",
                            Price = 679.99m,
                            SpecsJson = "{\"VRAM\":\"12GB\",\"BoostClock\":\"2.4GHz\",\"PCIe\":\"4.0\",\"Manufacturer\":\"Gigabyte\",\"Brand\":\"AMD\"}",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Low-budget AMD AM5 motherboard with very good price-to-performance ratio, capable of handling even more powerful CPUs.",
                            ImageUrl = "/images/products/asrock_b650m.jpg",
                            Name = "ASRock B650M-HDV/M.2",
                            Price = 169.99m,
                            SpecsJson = "{\"Socket\":\"AM5\",\"FormFactor\":\"Micro-ATX\",\"Chipset\":\"B650\"}",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Intel LGA1700 motherboard for 12th Gen CPUs with PCIe 5.0 support.",
                            ImageUrl = "/images/products/msi_z690a.jpg",
                            Name = "MSI Z690-A Pro",
                            Price = 259.99m,
                            SpecsJson = "{\"Socket\":\"LGA1700\",\"FormFactor\":\"ATX\",\"Chipset\":\"Z690\"}",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Affordable LGA1700 motherboard for mid-range builds.",
                            ImageUrl = "/images/products/gigabyte_b660m.jpg",
                            Name = "Gigabyte B660M DS3H",
                            Price = 129.99m,
                            SpecsJson = "{\"Socket\":\"LGA1700\",\"FormFactor\":\"Micro-ATX\",\"Chipset\":\"B660\"}",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "High-speed DDR4 memory kit, 3200MHz.",
                            ImageUrl = "/images/products/corsair_16gb.jpg",
                            Name = "Corsair Vengeance LPX 16GB",
                            Price = 69.99m,
                            SpecsJson = "{\"Capacity\":\"16GB\",\"Type\":\"DDR4\",\"Speed\":\"3200MHz\"}",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Premium DDR4 RAM with RGB lighting, 3600MHz.",
                            ImageUrl = "/images/products/gskill_32gb.jpg",
                            Name = "G.Skill Trident Z RGB 32GB",
                            Price = 209.99m,
                            SpecsJson = "{\"Capacity\":\"32GB\",\"Type\":\"DDR4\",\"Speed\":\"3600MHz\"}",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Reliable DDR4 memory for gaming and multitasking.",
                            ImageUrl = "/images/products/kingston_16gb.jpg",
                            Name = "Kingston Fury Beast 16GB",
                            Price = 109.99m,
                            SpecsJson = "{\"Capacity\":\"16GB\",\"Type\":\"DDR4\",\"Speed\":\"3200MHz\"}",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "High-speed NVMe SSD for gaming and productivity.",
                            ImageUrl = "/images/products/samsung_970evo.jpg",
                            Name = "Samsung 970 EVO Plus 250GB",
                            Price = 119.99m,
                            SpecsJson = "{\"Capacity\":\"250GB\",\"FormFactor\":\"M.2\",\"Interface\":\"NVMe\"}",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Reliable 2TB HDD for mass storage.",
                            ImageUrl = "/images/products/wd_2tb.jpg",
                            Name = "Western Digital Blue 2TB HDD",
                            Price = 59.99m,
                            SpecsJson = "{\"Capacity\":\"2TB\",\"FormFactor\":\"3.5in\",\"Interface\":\"SATA\"}",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "High-performance NVMe SSD with PCIe 4.0 support.",
                            ImageUrl = "/images/products/crucial_p5plus.jpg",
                            Name = "Crucial P5 Plus 1TB",
                            Price = 129.99m,
                            SpecsJson = "{\"Capacity\":\"1TB\",\"FormFactor\":\"M.2\",\"Interface\":\"NVMe\"}",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "750W 80+ Gold modular PSU with quiet operation.",
                            ImageUrl = "/images/products/corsair_rm750x.jpg",
                            Name = "Corsair RM750x",
                            Price = 169.99m,
                            SpecsJson = "{\"Wattage\":\"750W\",\"Efficiency\":\"80+ Gold\",\"Modular\":\"Yes\"}",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "Reliable 650W 80+ Gold fully modular power supply.",
                            ImageUrl = "/images/products/evga_650g5.jpg",
                            Name = "EVGA SuperNOVA 650 G5",
                            Price = 99.99m,
                            SpecsJson = "{\"Wattage\":\"650W\",\"Efficiency\":\"80+ Gold\",\"Modular\":\"No\"}",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "High-quality 850W PSU for high-end systems.",
                            ImageUrl = "/images/products/seasonic_850w.jpg",
                            Name = "Seasonic Focus GX-850",
                            Price = 239.99m,
                            SpecsJson = "{\"Wattage\":\"850W\",\"Efficiency\":\"80+ Gold\",\"Modular\":\"Yes\"}",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Description = "Low-budget single-tower air cooler for less demanding CPUs.",
                            ImageUrl = "/images/products/deepcool_ak400.jpg",
                            Name = "DeepCool AK400",
                            Price = 49.99m,
                            SpecsJson = "{\"Type\":\"Air Cooler\",\"Fans\":1}",
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "All-in-one liquid cooler with RGB lighting.",
                            ImageUrl = "/images/products/corsair_h100i.jpg",
                            Name = "Corsair iCUE H100i RGB",
                            Price = 169.99m,
                            SpecsJson = "{\"Type\":\"Liquid Cooler\",\"RadiatorSize\":\"240mm\"}",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Description = "Quiet and efficient air CPU cooler.",
                            ImageUrl = "/images/products/darkrock_pro4.jpg",
                            Name = "be quiet! Dark Rock Pro 4",
                            Price = 89.99m,
                            SpecsJson = "{\"Type\":\"Air Cooler\",\"Fans\":2}",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Description = "Mini-tower case with RGB fans, clean mesh design and exceptional airflow.",
                            ImageUrl = "/images/products/deepcool_ch360.jpg",
                            Name = "DeepCool CH360",
                            Price = 150.99m,
                            SpecsJson = "{\"FormFactor\":\"Mini Tower\",\"Color\":\"Black\"}",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Description = "High airflow mid-tower case with mesh front panel.",
                            ImageUrl = "/images/products/meshify_c.jpg",
                            Name = "Fractal Design Meshify C White",
                            Price = 120.99m,
                            SpecsJson = "{\"FormFactor\":\"Mid Tower\",\"Color\":\"White\"}",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            Description = "Compact mid-tower case optimized for airflow.",
                            ImageUrl = "/images/products/corsair_4000d.jpg",
                            Name = "Corsair 4000D Airflow",
                            Price = 99.99m,
                            SpecsJson = "{\"FormFactor\":\"Mid Tower\",\"Color\":\"Black\"}",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            Description = "Wired gaming mouse with adjustable DPI and 11 buttons.",
                            ImageUrl = "/images/products/logitech_g502.jpg",
                            Name = "Logitech G502 HERO",
                            Price = 109.99m,
                            SpecsJson = "{\"Type\":\"Mouse\",\"DPI\":\"16000\",\"Buttons\":11,\"Connectivity\":\"Wired\",\"RGB\":\"No\"}",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            Description = "Mechanical gaming keyboard with Cherry MX switches.",
                            ImageUrl = "/images/products/corsair_k70.jpg",
                            Name = "Corsair K70 RGB MK.2",
                            Price = 129.99m,
                            SpecsJson = "{\"Type\":\"Keyboard\",\"Switch\":\"Cherry MX Red\",\"Keys\":104,\"Connectivity\":\"Wired\",\"RGB\":\"Yes\"}",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            Description = "Ergonomic gaming mouse with high-precision optical sensor.",
                            ImageUrl = "/images/products/razer_deathadder_v2.jpg",
                            Name = "Razer DeathAdder V2",
                            Price = 69.99m,
                            SpecsJson = "{\"Type\":\"Mouse\",\"DPI\":\"20000\",\"Buttons\":8,\"Connectivity\":\"Wired\",\"RGB\":\"No\"}",
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            Description = "27-inch 4K IPS monitor with excellent color accuracy.",
                            ImageUrl = "/images/products/dell_u2720q.jpg",
                            Name = "Dell UltraSharp U2720Q",
                            Price = 499.99m,
                            SpecsJson = "{\"Size\":\"27in\",\"Resolution\":\"3840x2160\",\"Panel\":\"IPS\",\"RefreshRate\":\"60Hz\"}",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 10,
                            Description = "27-inch QHD gaming monitor with 165Hz refresh rate.",
                            ImageUrl = "/images/products/asus_vg27aq.jpg",
                            Name = "ASUS TUF Gaming VG27AQ",
                            Price = 399.99m,
                            SpecsJson = "{\"Size\":\"27in\",\"Resolution\":\"2560x1440\",\"Panel\":\"IPS\",\"RefreshRate\":\"165Hz\"}",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 10,
                            Description = "24-inch FHD gaming monitor with 180Hz refresh rate and a VA panel.",
                            ImageUrl = "/images/products/odyssey_g3.jpg",
                            Name = "Samsung Odyssey G3",
                            Price = 249.99m,
                            SpecsJson = "{\"Size\":\"24in\",\"Resolution\":\"1920x1080\",\"Panel\":\"VA\",\"RefreshRate\":\"180Hz\"}",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 9,
                            Description = "Tenkeyless mechanical gaming keyboard with Razer linear switches.",
                            ImageUrl = "/images/products/razer_huntsman.jpg",
                            Name = "Razer Hunstman V2 TKL",
                            Price = 169.99m,
                            SpecsJson = "{\"Type\":\"Keyboard\",\"Switch\":\"Razer\",\"Keys\":88,\"Connectivity\":\"Wired\",\"RGB\":\"Yes\"}",
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("TechHaven.Data.Models.ProductSale", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSales");
                });

            modelBuilder.Entity("TechHaven.Data.Models.WishlistItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechHaven.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechHaven.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechHaven.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechHaven.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechHaven.Data.Models.Order", b =>
                {
                    b.HasOne("TechHaven.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechHaven.Data.Models.Product", b =>
                {
                    b.HasOne("TechHaven.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechHaven.Data.Models.ProductSale", b =>
                {
                    b.HasOne("TechHaven.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechHaven.Data.Models.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechHaven.Data.Models.WishlistItem", b =>
                {
                    b.HasOne("TechHaven.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechHaven.Data.Models.ApplicationUser", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechHaven.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("TechHaven.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TechHaven.Data.Models.Product", b =>
                {
                    b.Navigation("ProductSales");
                });
#pragma warning restore 612, 618
        }
    }
}
